{{ config(materialized='view') }}

WITH source AS (
    SELECT * FROM {{ source('ipl_dataset', 'raw_ipl_stats') }}
)

SELECT
    Player,
    COUNTRY,
    TEAM,
    AGE,
    `CAPTAINCY EXP` AS captaincy_exp,
    Paying_Role,
    Mat,
    Inns,
    Runs,
    BF,
    HS,
    `Avg` AS batting_avg,
    `SR` AS strike_rate,
    `NO` AS not_outs,
    `4s` AS num_4s,
    `6s` AS num_6s,
    `0s` AS ducks,
    `50s` AS fifties,
    `100s` AS hundreds,
    TMat,
    TInns,
    TRuns,
    TBF,
    THS,
    TAvg,
    TSR,
    TNO,
    T4s AS total_4s,
    T6s AS total_6s,
    T0s AS total_ducks,
    T50s AS total_fifties,
    T100s AS total_hundreds,
    B_Inns,
    B_Balls,
    B_Runs,
    B_Maidens,
    B_Wkts,
    B_Avg,
    B_Econ,
    B_SR,
    B_4w,
    B_5w,
    B_TInns,
    B_TBalls,
    B_TRuns,
    B_TMaidens,
    B_TWkts,
    B_TAvg,
    B_TEcon,
    B_TSR,
    B_T4w,
    B_T5w,
    SOLD_PRICE

FROM source
