FROM bitnami/spark:3.4.1

USER root

# Copy GCP credentials and jars
COPY ./ipl-streaming-project-*.json /app/
COPY ./jars/*.jar /opt/bitnami/spark/jars/

# Copy your project files
COPY . /app
WORKDIR /app
